### ISSUE TITLE
NGSderive step assumes plain text

### ISSUE THREAD

**Issue by adthrasher** [stjudecloud/workflows#15]
All of the other steps that use the GTF file seem to properly handle compressed input, but this step requires the file to be plain-text. It should handle compressed input appropriately. https://github.com/stjudecloud/workflows/blob/f19e0d3a9dc5d685519b1a42b77e6d41121eac3c/tools/ngsderive.wdl#L21

**Comment by a-frantz** [comment]
This has been resolved
