### ISSUE TITLE
Modularize QC

### ISSUE THREAD

**Issue by a-frantz** [stjudecloud/workflows#84]
The analyses run should be toggle-able for users only interested in a subset of the workflow (and to keep costs down)

**Comment by adthrasher** [comment]
I agree with your end conclusion. I think this isn't something to pursue at the moment. It would be a "nice to have" feature if we could do it cleanly, but having `if` statements around every call, the inputs required to support that, and making the outputs optional seems like it would significantly impact the clarity of the workflow. It is relatively simple to grab a copy of the workflow and delete unwanted steps or to write a workflow from scratch that uses our tasks if someone were to desire that. If we had concrete use cases for disabling some analyses (similar to the ones we currently have), then we could pursue that.
